In [4]:
import random

In [5]:
print(random.randrange(50000,150000))

71960


In [6]:
# create a list of 1,000,000 salaries ranging from 50,000 to 150,000


salaries = []

for i in range(1000000):
  salaries.append(random.randint(50000,150000))

In [7]:
sum(salaries)/len(salaries)

99995.405043

In [8]:
salary_list = [random.randint(50_000,150_000) for i in range(10_000_000)]

In [9]:
%%timeit

sum(salary_list)/len(salary_list)

91.4 ms ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
import statistics

In [11]:
%%timeit

statistics.mean(salary_list)

2.58 s ± 309 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
import numpy as np

In [13]:
%%timeit

np.mean(salary_list)

716 ms ± 212 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
my_array = np.array([1,2,3,4])

In [15]:
my_array

array([1, 2, 3, 4])

In [16]:
my_array.mean()

np.float64(2.5)

In [17]:
print(np.mean(my_array))

2.5


In [18]:
years_of_experience = np.array([1, 2, 3, 4, 5])

years_of_experience = years_of_experience + 1

In [19]:
years_of_experience

array([2, 3, 4, 5, 6])

In [20]:
years_of_experience = years_of_experience - 1

years_of_experience

array([1, 2, 3, 4, 5])

In [21]:
years_of_experience_half = years_of_experience / 2

years_of_experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

# slicing

In [22]:
second_and_third_jobs_experience = years_of_experience[1:3]

second_and_third_jobs_experience

array([2, 3])

In [24]:
print(years_of_experience[-1])

5


# boolean indexing

In [25]:
years_of_experience[years_of_experience > 2]

array([3, 4, 5])

# mathematical statistics

In [27]:
print(np.sum(years_of_experience))

15


In [28]:
print(np.mean(years_of_experience))

3.0


In [29]:
print(np.cumsum(years_of_experience))

[ 1  3  6 10 15]


In [30]:
print(np.cumprod(years_of_experience))

[  1   2   6  24 120]


In [31]:
print(np.std(years_of_experience))

1.4142135623730951


In [32]:
print(np.var(years_of_experience))

2.0


In [33]:
print(np.min(years_of_experience))

1


In [34]:
print(np.max(years_of_experience))

5


# NaN

np.nan

In [50]:
type(np.nan)

float

In [51]:
salary_with_nan = np.array([123_124, np.nan, 145_000, 128_000, 110_000, 149_999, np.nan, 135_000, 115_000, 140_000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [52]:
np.mean(salary_with_nan)

np.float64(nan)

In [53]:
np.nanmean(salary_with_nan)

np.float64(130765.375)

In [38]:
# Replace Values with NaN

salary_with_nan[salary_with_nan < 130_000] = np.nan

salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

In [41]:
# where
# Replace values using np.where
# np.where(condition, if condition is true, if condition is false)

salary_with_nan = np.where(salary_with_nan < 120000, 120000, salary_with_nan)
salary_with_nan

array([123124.,     nan, 145000., 128000., 120000., 149999.,     nan,
       135000., 120000., 140000.])

In [42]:
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'AI Engineer'])

base_salaries = np.array([60_000, 80_000, 75_000, 90_000, np.nan])

bonus_rates = np.array([0.05, 0.10, 0.08, 0.12, np.nan], dtype = float)

In [46]:
total_salaries = base_salaries * (1 + bonus_rates)

In [48]:
total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [49]:
np.mean(total_salaries)

np.float64(83200.0)

In [54]:
applications_list = [10, 15, 7, 20, 25, 30, 5]
applications = np.array(applications_list)

In [55]:
applications

array([10, 15,  7, 20, 25, 30,  5])

In [56]:

postings_list = [10, 15, 7, 20, 25, 30, 5]

postings = np.array(postings_list)

In [57]:
postings[0:3]

array([10, 15,  7])

In [58]:
salaries_list = [70000, 85000, 60000, 95000, 80000]

salaries = np.array(salaries_list)

print(np.max(salaries))
print(np.min(salaries))

95000
60000
